version: '3.9'

volumes:
  pg_data_production:
  static_volume:

services:
  db:
    env_file: .env
    image: postgres:13.11
    volumes:
      - pg_data_production:/var/lib/postgresql/data

  backend:
    env_file: .env
    image: ${DOCKER_LOGIN}/taski_backend
    volumes:
      - static_volume:/backend_static

  frontend:
    env_file: .env
    image: ${DOCKER_LOGIN}/taski_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static

  gateway:
    env_file: .env
    image: ${DOCKER_LOGIN}/taski_gateway
    volumes:
      - static_volume:/staticfiles/
    ports:
      - ${NGINX_PORT}:80